spring:
  application:
    name: book
  profiles:
    default: local
  config:
    import: classpath:persistence.yml

auth:
  cookie:
    secure: ${AUTH_COOKIE_SECURE:false}
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
  token:
    secret: ${JWT_SECRET}
    access-token-expiration: 1h
    refresh-token-expiration: 7d
