spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/book}
    username: ${DB_USERNAME:book}
    password: ${DB_PASSWORD}
